control: 
  model: cl4st
  testonly: 0
  device: cuda:0
  mdir: ./results/model/
  logdir: ./results/log/
  date: 2023y10m25d

data:
  dataset: PEMS4
  data_path: ./data/county/covid19_2020_01_23_2022_07_31_921x3249x5_county_csse_new.h5
  val_ratio: 0.2
  test_ratio: 0.2
  lag: 12
  horizon: 12
  batch_size: 32
  geo_graph: ./data/county/geo_geaph_county_full.cpt
  num_nodes: 307
  trend_flg: 1
  adj_filename: ./data/PEMS04/PEMS04.csv
  id_filename: None

training:
  patience: 20
  model_path: ./results/model/2022y9m5d/STID.pkl
  mae_thresh: 0.0
  mape_thresh: 0.0
  lr: 0.001
  # weight_decay: 0.0001
  weight_decay: 0.0
  lr_decay_ratio: 0.5
  steps: [1, 50, 100]
  criterion: 'Smooth'
  max_epoch: 200
  grad_norm: 1

model:
# GIB
  reparam_mode: "diag"
  prior_mode: "mixGau-100"
  struct_dropout_mode: 0
  
  only_spat: 0
  beta1: 1
  beta2: 1
  gib_drop: 0.3
  spat_gsat: 1
  temp_gsat: 1

  # cl4st
  view_num: 1
  cr: 0.8
  cr_init: 0.2
  cl_temp: 0.5
  is_anneal: 1
  sim_spat_coeff_init: 0.2
  sim_spat_coeff: 0.8
  sim_temp_coeff_init: 0.2
  sim_temp_coeff: 0.8

  is_anneal_kld: 0

  kld_spat_coeff_init: 0.1
  kld_spat_coeff: 1
  kld_temp_coeff_init: 0.05
  kld_temp_coeff: 1

  loss_mode: 'sum_loss'
  
  
  dynamic: 1
  
  debug: 1
  non_node: 0

  head: [4, 1]
  mem_size: 16
  d_model_temp: 128
  d_model_spat: 64